In [2]:
import glob

import h5py
import numpy as np
import pandas as pd

In [6]:
h5_path = './data/cd1_predicted_frames/CAGE4_TUBETEST_1v2.fixed.mp4.predictions.000_CAGE4_TUBETEST_1v2.fixed.analysis.h5'

In [3]:
dataset = h5py.File('./data/cd1_predicted_frames/CAGE4_TUBETEST_1v2.fixed.mp4.predictions.000_CAGE4_TUBETEST_1v2.fixed.analysis.h5', 'r')

- Options
    - Separate the video by each side of the tube
    - Keep the sides together

In [5]:
dataset.keys()

<KeysViewHDF5 ['edge_inds', 'edge_names', 'instance_scores', 'labels_path', 'node_names', 'point_scores', 'provenance', 'track_names', 'track_occupancy', 'tracking_scores', 'tracks', 'video_ind', 'video_path']>

In [17]:
df = pd.read_hdf(h5_path)

ValueError: Dataset(s) incompatible with Pandas data types, not table, or no datasets found in HDF5 file.

In [15]:
example_df = pd.read_csv("./data/video-1.csv", index_col=0, header=[0,1,2])

In [16]:
example_df

scorer    DeepCut_resnet50_VAME-FinalNov7shuffle1_350000              \
bodyparts                                           Nose               
coords                                                 x           y   
0                                             379.317975  911.234954   
1                                             352.770493  932.695036   
2                                             323.450306  952.783498   
3                                             322.339995  957.686823   
4                                             321.909653  961.421213   
...                                                  ...         ...   
29992                                         677.533519  578.745465   
29993                                         679.119630  574.885421   
29994                                         678.925062  573.722989   
29995                                         679.336848  574.966761   
29996                                         680.833259  575.649763   

scorer                                                                    \
bodyparts            Forehand-Left                        Forehand-Right   
coords    likelihood             x           y likelihood              x   
0                1.0    323.975258  863.344640        1.0     374.574893   
1                1.0    324.490868  862.656106        1.0     373.739357   
2                1.0    312.932200  887.286848        1.0     348.825588   
3                1.0    310.915744  899.386683        1.0     349.146741   
4                1.0    309.072843  909.602562        1.0     349.270147   
...              ...           ...         ...        ...            ...   
29992            1.0    636.415181  564.477034        1.0     682.732976   
29993            1.0    636.945385  563.419916        1.0     682.355730   
29994            1.0    639.467558  561.507620        1.0     682.160960   
29995            1.0    639.000703  560.229738        1.0     682.378444   
29996            1.0    638.583565  560.297896        1.0     682.420940   

scorer                                                                 \
bodyparts                        Hindhand-Left                          
coords              y likelihood             x           y likelihood   
0          868.388032        1.0    235.991503  750.109876        1.0   
1          877.411902        1.0    260.993583  793.434588        1.0   
2          905.028284        1.0    277.930833  822.808193        1.0   
3          904.790210        1.0    278.165046  822.775362        1.0   
4          904.706641        1.0    278.351273  822.240499        1.0   
...               ...        ...           ...         ...        ...   
29992      541.689991        1.0    587.515024  510.388803        1.0   
29993      541.394161        1.0    587.436843  510.181781        1.0   
29994      541.240808        1.0    587.457818  509.340193        1.0   
29995      541.277768        1.0    587.305794  509.271055        1.0   
29996      541.463179        1.0    587.183496  509.264368        1.0   

scorer                                                                   \
bodyparts Hindhand-Right                           Tailroot               
coords                 x           y likelihood           x           y   
0             320.932527  727.344460        1.0  287.096150  712.359906   
1             318.921153  727.962605        1.0  290.610608  734.828937   
2             320.172479  730.966355        1.0  293.222581  747.546816   
3             320.457282  731.553658        1.0  296.795987  749.779550   
4             320.698215  732.265580        1.0  299.903449  753.269333   
...                  ...         ...        ...         ...         ...   
29992         651.346715  462.211248        1.0  581.673425  434.102119   
29993         651.538346  462.225548        1.0  580.899144  433.592916   
29994         651.453834  462.245982        1.0  580.846196  433.225684   
299

In [ ]:
example_df[]

In [63]:
with h5py.File(h5_path, "r") as f:
    dset_names = list(f.keys())
    locations = f["tracks"][:].T
    tracking_scores = f["tracking_scores"][:]
    instances_scores = f["instance_scores"][:]
    node_names = [n.decode() for n in f["node_names"][:]]


In [64]:
print("===HDF5 datasets===")
print(dset_names)
print()

print("===locations data shape===")
print(locations.shape)
print()

print("===nodes===")
for i, name in enumerate(node_names):
    print(f"{i}: {name}")
print()

===HDF5 datasets===
['edge_inds', 'edge_names', 'instance_scores', 'labels_path', 'node_names', 'point_scores', 'provenance', 'track_names', 'track_occupancy', 'tracking_scores', 'tracks', 'video_ind', 'video_path']

===locations data shape===
(194, 6, 2, 2)

===nodes===
0: ear
1: nose
2: tail_base
3: thorax
4: front_foot
5: rear_foot



In [65]:
locations

array([[[[ 636.18554688, 1315.63500977],
         [ 763.41711426,  764.22235107]],

        [[ 731.88220215, 1207.74133301],
         [ 839.62005615,  835.98730469]],

        [[ 224.43968201,           nan],
         [ 752.24365234,           nan]],

        [[ 444.06677246, 1403.75061035],
         [ 736.12164307,  736.31848145]],

        [[ 559.8215332 , 1287.79211426],
         [ 856.13677979,  883.53204346]],

        [[ 168.12338257,           nan],
         [ 887.70623779,           nan]]],


       [[[ 680.47436523, 1240.11132812],
         [ 764.23657227,  771.94647217]],

        [[ 775.67022705, 1136.28613281],
         [ 840.25872803,  844.39770508]],

        [[ 267.95581055, 1656.20471191],
         [ 787.62969971,  792.44732666]],

        [[ 504.30621338, 1431.85974121],
         [ 728.2098999 ,  743.88330078]],

        [[ 564.33746338, 1279.53369141],
         [ 855.76104736,  879.46813965]],

        [[          nan, 1663.79040527],
         [          nan,  872.431

In [66]:
frame_count, node_count, _, instance_count = locations.shape

print("frame count:", frame_count)
print("node count:", node_count)
print("instance count:", instance_count)

frame count: 194
node count: 6
instance count: 2


In [67]:
from scipy.interpolate import interp1d

def fill_missing(Y, kind="linear"):
    """Fills missing values independently along each dimension after the first."""

    # Store initial shape.
    initial_shape = Y.shape

    # Flatten after first dim.
    Y = Y.reshape((initial_shape[0], -1))

    # Interpolate along each slice.
    for i in range(Y.shape[-1]):
        y = Y[:, i]

        # Build interpolant.
        x = np.flatnonzero(~np.isnan(y))
        f = interp1d(x, y[x], kind=kind, fill_value=np.nan, bounds_error=False)

        # Fill missing
        xq = np.flatnonzero(np.isnan(y))
        y[xq] = f(xq)
        
        # Fill leading or trailing NaNs with the nearest non-NaN values
        mask = np.isnan(y)
        y[mask] = np.interp(np.flatnonzero(mask), np.flatnonzero(~mask), y[~mask])

        # Save slice
        Y[:, i] = y

    # Restore to initial shape.
    Y = Y.reshape(initial_shape)

    return Y

In [68]:
locations = fill_missing(locations)

In [69]:
HEAD_INDEX = 0
THORAX_INDEX = 1
ABDO_INDEX = 2

In [70]:
head_loc = locations[:, HEAD_INDEX, :, :]
thorax_loc = locations[:, THORAX_INDEX, :, :]
abdo_loc = locations[:, ABDO_INDEX, :, :]

In [72]:
locations.shape

(194, 6, 2, 2)

- SLEAP coordinates
    - frame number, node number, x or y, id number

- X coordinate is 0, Y coordinate is 1

In [73]:
locations[0][0]

array([[ 636.18554688, 1315.63500977],
       [ 763.41711426,  764.22235107]])

In [74]:
locations[100][0]

array([[807.97918701, 816.16604614],
       [748.00238037, 769.96801758]])

In [75]:
locations[190][0][1]

array([751.7901001, 755.9498291])

In [76]:
locations[:, 0, 0, 0]

array([ 636.18554688,  680.47436523,  715.9987793 ,  771.855896  ,
        827.88275146,  839.89123535,  835.81665039,  824.12072754,
        820.20666504,  823.92272949,  832.19024658,  839.95068359,
        851.86431885,  852.27661133,  851.9161377 ,  847.76660156,
        836.38787842,  836.37268066,  840.05383301,  852.03717041,
        870.07324219,  888.10931396,  864.08325195,  844.08752441,
        816.04382324,  819.61529541,  848.05718994,  860.03613281,
        883.84130859,  884.40637207,  876.52850342,  859.6038208 ,
        848.3168335 ,  855.93341064,  868.24139404,  855.89404297,
        843.89520264,  860.059021  ,  864.30053711,  864.14373779,
        864.36187744,  831.50213623,  900.09375   ,  907.59606934,
        896.00823975,  895.94885254,  896.15307617,  904.00921631,
        906.17596436,  908.3427124 ,  902.2880249 ,  896.2333374 ,
        896.22851562,  903.61737061,  912.37158203,  919.965271  ,
        936.37457275,  955.89367676,  964.1697998 ,  956.43377

In [77]:
locations.shape

(194, 6, 2, 2)

In [78]:
locations[:,:,:,0]

array([[[636.18554688, 763.41711426],
        [731.88220215, 839.62005615],
        [224.43968201, 752.24365234],
        [444.06677246, 736.12164307],
        [559.8215332 , 856.13677979],
        [168.12338257, 887.70623779]],

       [[680.47436523, 764.23657227],
        [775.67022705, 840.25872803],
        [267.95581055, 787.62969971],
        [504.30621338, 728.2098999 ],
        [564.33746338, 855.76104736],
        [302.61659749, 877.08459473]],

       [[715.9987793 , 760.16168213],
        [816.02160645, 835.62127686],
        [343.76968384, 775.77478027],
        [555.70288086, 731.76989746],
        [727.97674561, 848.21002197],
        [437.10981242, 866.46295166]],

       ...,

       [[407.81848145, 751.7901001 ],
        [440.12734985, 764.06341553],
        [147.87149048, 844.17193604],
        [255.85533142, 720.01757812],
        [436.09719849, 871.95184326],
        [123.85195923, 880.06799316]],

       [[407.81848145, 751.7901001 ],
        [440.12734985, 764.06

In [37]:
def produce_df(rows, columns, row_names=None, column_names=None):
    """rows is a list of lists that will be used to build a MultiIndex
    columns is a list of lists that will be used to build a MultiIndex"""
    row_index = pd.MultiIndex.from_product(rows, names=row_names)
    col_index = pd.MultiIndex.from_product(columns, names=column_names)
    return pd.DataFrame(index=row_index, columns=col_index)

In [43]:
produce_df([['a', 'b']], [node_names, ['x', 'y']])


ear      nose      tail_base      thorax      front_foot      rear_foot  \
     x    y    x    y         x    y      x    y          x    y         x   
a  NaN  NaN  NaN  NaN       NaN  NaN    NaN  NaN        NaN  NaN       NaN   
b  NaN  NaN  NaN  NaN       NaN  NaN    NaN  NaN        NaN  NaN       NaN   

        
     y  
a  NaN  
b  NaN

In [39]:
node_names

['ear', 'nose', 'tail_base', 'thorax', 'front_foot', 'rear_foot']

In [54]:
instances_scores.shape

(2, 194)

In [53]:
tracking_scores

array([[          nan,  -60.09309769, -100.22259521,  -54.80153656,
         -15.63673973,  -10.24626732,   -9.22846603,   -2.67489958,
          -0.32433128,   -0.73331463,   -3.07362914,   -6.64051628,
          -7.30306911,   -3.73756838,   -5.03766775,  -75.62200165,
          -8.53457642,   -7.05034494,  -31.60495567,   -4.25989389,
         -46.05050659,  -38.78982544,  -48.99094391,  -28.59298706,
         -29.63674355,  -26.98335075,   -7.85521555,   -8.05189228,
          -4.20230198,   -6.68486738,   -9.52558708,   -6.74027109,
          -3.03634191,  -48.7921257 ,  -48.12660599,  -53.58452225,
         -58.90586472,  -10.65644264,  -51.15689468,   -1.80665171,
         -22.71046638,  -20.84678459,  -14.03412056,  -24.31245995,
         -22.00974274,   -4.0145793 ,  -31.80082893,  -50.56274414,
          -1.02093506,  -52.80811691,   -1.79668963,  -87.19734192,
         -54.07027817,  -73.33692932,   -9.53038406,   -6.73071575,
         -12.23271179,  -27.28444672,  -47.55476

In [55]:
a=np.arange(24).reshape((3,2,2,2))
iterables=[[1,2,3],[1,2],['m1','m2'],['A','B']]
index = pd.MultiIndex.from_product(iterables, names=['time','sub','meas','cond'])

pd.DataFrame(a.reshape(24, 1),index=index)

0
time sub meas cond    
1    1   m1   A      0
              B      1
         m2   A      2
              B      3
     2   m1   A      4
              B      5
         m2   A      6
              B      7
2    1   m1   A      8
              B      9
         m2   A     10
              B     11
     2   m1   A     12
              B     13
         m2   A     14
              B     15
3    1   m1   A     16
              B     17
         m2   A     18
              B     19
     2   m1   A     20
              B     21
         m2   A     22
              B     23

In [57]:
a.shape

(3, 2, 2, 2)

- Getting all the coordinates for only one animal

In [79]:
locations[:,:,:,0]

array([[[636.18554688, 763.41711426],
        [731.88220215, 839.62005615],
        [224.43968201, 752.24365234],
        [444.06677246, 736.12164307],
        [559.8215332 , 856.13677979],
        [168.12338257, 887.70623779]],

       [[680.47436523, 764.23657227],
        [775.67022705, 840.25872803],
        [267.95581055, 787.62969971],
        [504.30621338, 728.2098999 ],
        [564.33746338, 855.76104736],
        [302.61659749, 877.08459473]],

       [[715.9987793 , 760.16168213],
        [816.02160645, 835.62127686],
        [343.76968384, 775.77478027],
        [555.70288086, 731.76989746],
        [727.97674561, 848.21002197],
        [437.10981242, 866.46295166]],

       ...,

       [[407.81848145, 751.7901001 ],
        [440.12734985, 764.06341553],
        [147.87149048, 844.17193604],
        [255.85533142, 720.01757812],
        [436.09719849, 871.95184326],
        [123.85195923, 880.06799316]],

       [[407.81848145, 751.7901001 ],
        [440.12734985, 764.06

SLEAP coordinates
frame number, node number, x or y, id numberm

In [80]:
locations[:,:,:,0][0]

array([[636.18554688, 763.41711426],
       [731.88220215, 839.62005615],
       [224.43968201, 752.24365234],
       [444.06677246, 736.12164307],
       [559.8215332 , 856.13677979],
       [168.12338257, 887.70623779]])

- Getting coordinates for one animal and one axis

In [82]:
locations[:,:,0,0]

array([[636.18554688, 731.88220215, 224.43968201, 444.06677246,
        559.8215332 , 168.12338257],
       [680.47436523, 775.67022705, 267.95581055, 504.30621338,
        564.33746338, 302.61659749],
       [715.9987793 , 816.02160645, 343.76968384, 555.70288086,
        727.97674561, 437.10981242],
       ...,
       [407.81848145, 440.12734985, 147.87149048, 255.85533142,
        436.09719849, 123.85195923],
       [407.81848145, 440.12734985, 147.87149048, 255.85533142,
        436.09719849, 123.85195923],
       [407.81848145, 440.12734985, 147.87149048, 255.85533142,
        436.09719849, 123.85195923]])

In [83]:
locations[:,:,:,0].shape

(194, 6, 2)

In [85]:
m,n,r = locations[:,:,:,0].shape
out_arr = np.column_stack((np.repeat(np.arange(m),n),locations[:,:,:,0].reshape(m*n,-1)))
out_df = pd.DataFrame(out_arr)

In [86]:
out_df

0           1           2
0       0.0  636.185547  763.417114
1       0.0  731.882202  839.620056
2       0.0  224.439682  752.243652
3       0.0  444.066772  736.121643
4       0.0  559.821533  856.136780
...     ...         ...         ...
1159  193.0  440.127350  764.063416
1160  193.0  147.871490  844.171936
1161  193.0  255.855331  720.017578
1162  193.0  436.097198  871.951843
1163  193.0  123.851959  880.067993

[1164 rows x 3 columns]

In [89]:
locations[:,:,0,0]

array([[636.18554688, 731.88220215, 224.43968201, 444.06677246,
        559.8215332 , 168.12338257],
       [680.47436523, 775.67022705, 267.95581055, 504.30621338,
        564.33746338, 302.61659749],
       [715.9987793 , 816.02160645, 343.76968384, 555.70288086,
        727.97674561, 437.10981242],
       ...,
       [407.81848145, 440.12734985, 147.87149048, 255.85533142,
        436.09719849, 123.85195923],
       [407.81848145, 440.12734985, 147.87149048, 255.85533142,
        436.09719849, 123.85195923],
       [407.81848145, 440.12734985, 147.87149048, 255.85533142,
        436.09719849, 123.85195923]])

In [88]:
locations[:,:,:,0].transpose(2,0,1).reshape(3,-1)

array([[636.18554688, 731.88220215, 224.43968201, ..., 665.32248942,
        752.17095947, 798.02960205],
       [512.1338501 , 639.76861572, 818.686561  , ..., 852.06243896,
        831.59442139, 728.4574585 ],
       [848.08789062, 855.96240234, 796.378479  , ..., 720.01757812,
        871.95184326, 880.06799316]])

In [92]:
locations[:,:,:,0][0]

array([[636.18554688, 763.41711426],
       [731.88220215, 839.62005615],
       [224.43968201, 752.24365234],
       [444.06677246, 736.12164307],
       [559.8215332 , 856.13677979],
       [168.12338257, 887.70623779]])

In [91]:
locations[:,:,:,0][0].shape

(6, 2)

In [96]:
animal_1_array = locations[:,:,:,0].reshape(locations[:,:,:,0].shape[0], (locations[:,:,:,0].shape[1]*locations[:,:,:,0].shape[2]))

In [97]:
animal_1_array

array([[636.18554688, 763.41711426, 731.88220215, ..., 856.13677979,
        168.12338257, 887.70623779],
       [680.47436523, 764.23657227, 775.67022705, ..., 855.76104736,
        302.61659749, 877.08459473],
       [715.9987793 , 760.16168213, 816.02160645, ..., 848.21002197,
        437.10981242, 866.46295166],
       ...,
       [407.81848145, 751.7901001 , 440.12734985, ..., 871.95184326,
        123.85195923, 880.06799316],
       [407.81848145, 751.7901001 , 440.12734985, ..., 871.95184326,
        123.85195923, 880.06799316],
       [407.81848145, 751.7901001 , 440.12734985, ..., 871.95184326,
        123.85195923, 880.06799316]])

In [99]:
header = pd.MultiIndex.from_product([node_names,
                                     ['x', 'y']],
                                    names=['nodes','xy'])

In [100]:
pd.DataFrame(animal_1_array, columns=header)

nodes         ear                    nose               tail_base              \
xy              x           y           x           y           x           y   
0      636.185547  763.417114  731.882202  839.620056  224.439682  752.243652   
1      680.474365  764.236572  775.670227  840.258728  267.955811  787.629700   
2      715.998779  760.161682  816.021606  835.621277  343.769684  775.774780   
3      771.855896  771.493469  867.729797  843.865845  395.809326  775.524414   
4      827.882751  767.876892  919.877197  839.806763  440.052307  764.176453   
..            ...         ...         ...         ...         ...         ...   
189    360.130463  743.406555  455.833435  768.313965  147.871490  844.171936   
190    407.818481  751.790100  440.127350  764.063416  147.871490  844.171936   
191    407.818481  751.790100  440.127350  764.063416  147.871490  844.171936   
192    407.818481  751.790100  440.127350  764.063416  147.871490  844.171936   
193    407.818481  751.790100  440.127350  764.063416  147.871490  844.171936   

nodes      thorax              front_foot               rear_foot              
xy              x           y           x           y           x           y  
0      444.066772  736.121643  559.821533  856.136780  168.123383  887.706238  
1      504.306213  728.209900  564.337463  855.761047  302.616597  877.084595  
2      555.702881  731.769897  727.976746  848.210022  437.109812  866.462952  
3      623.946594  724.140747  771.931091  864.343689  571.603027  855.841309  
4      659.968140  723.991455  791.741943  868.098816  580.077698  855.778442  
..            ...         ...         ...         ...         ...         ...  
189    299.962158  723.643066  436.097198  871.951843  127.941246  880.165527  
190    255.855331  720.017578  436.097198  871.951843  123.851959  880.067993  
191    255.855331  720.017578  436.097198  871.951843  123.851959  880.067993  
192    255.855331  720.017578  436.097198  871.951843  123.851959  880.067993  
193    255.855331  720.017578  436.097198  871.951843  123.851959  880.067993  

[194 rows x 12 columns]