In [143]:
import glob

import h5py
import numpy as np
import pandas as pd
import os

In [6]:
h5_path = './data/cd1_predicted_frames/CAGE4_TUBETEST_1v2.fixed.mp4.predictions.000_CAGE4_TUBETEST_1v2.fixed.analysis.h5'

In [3]:
dataset = h5py.File('./data/cd1_predicted_frames/CAGE4_TUBETEST_1v2.fixed.mp4.predictions.000_CAGE4_TUBETEST_1v2.fixed.analysis.h5', 'r')

- Options
    - Separate the video by each side of the tube
    - Keep the sides together

In [5]:
dataset.keys()

<KeysViewHDF5 ['edge_inds', 'edge_names', 'instance_scores', 'labels_path', 'node_names', 'point_scores', 'provenance', 'track_names', 'track_occupancy', 'tracking_scores', 'tracks', 'video_ind', 'video_path']>

In [17]:
df = pd.read_hdf(h5_path)

ValueError: Dataset(s) incompatible with Pandas data types, not table, or no datasets found in HDF5 file.

In [15]:
example_df = pd.read_csv("./data/video-1.csv", index_col=0, header=[0,1,2])

In [16]:
example_df

scorer    DeepCut_resnet50_VAME-FinalNov7shuffle1_350000              \
bodyparts                                           Nose               
coords                                                 x           y   
0                                             379.317975  911.234954   
1                                             352.770493  932.695036   
2                                             323.450306  952.783498   
3                                             322.339995  957.686823   
4                                             321.909653  961.421213   
...                                                  ...         ...   
29992                                         677.533519  578.745465   
29993                                         679.119630  574.885421   
29994                                         678.925062  573.722989   
29995                                         679.336848  574.966761   
29996                                         680.833259  575.649763   

scorer                                                                    \
bodyparts            Forehand-Left                        Forehand-Right   
coords    likelihood             x           y likelihood              x   
0                1.0    323.975258  863.344640        1.0     374.574893   
1                1.0    324.490868  862.656106        1.0     373.739357   
2                1.0    312.932200  887.286848        1.0     348.825588   
3                1.0    310.915744  899.386683        1.0     349.146741   
4                1.0    309.072843  909.602562        1.0     349.270147   
...              ...           ...         ...        ...            ...   
29992            1.0    636.415181  564.477034        1.0     682.732976   
29993            1.0    636.945385  563.419916        1.0     682.355730   
29994            1.0    639.467558  561.507620        1.0     682.160960   
29995            1.0    639.000703  560.229738        1.0     682.378444   
29996            1.0    638.583565  560.297896        1.0     682.420940   

scorer                                                                 \
bodyparts                        Hindhand-Left                          
coords              y likelihood             x           y likelihood   
0          868.388032        1.0    235.991503  750.109876        1.0   
1          877.411902        1.0    260.993583  793.434588        1.0   
2          905.028284        1.0    277.930833  822.808193        1.0   
3          904.790210        1.0    278.165046  822.775362        1.0   
4          904.706641        1.0    278.351273  822.240499        1.0   
...               ...        ...           ...         ...        ...   
29992      541.689991        1.0    587.515024  510.388803        1.0   
29993      541.394161        1.0    587.436843  510.181781        1.0   
29994      541.240808        1.0    587.457818  509.340193        1.0   
29995      541.277768        1.0    587.305794  509.271055        1.0   
29996      541.463179        1.0    587.183496  509.264368        1.0   

scorer                                                                   \
bodyparts Hindhand-Right                           Tailroot               
coords                 x           y likelihood           x           y   
0             320.932527  727.344460        1.0  287.096150  712.359906   
1             318.921153  727.962605        1.0  290.610608  734.828937   
2             320.172479  730.966355        1.0  293.222581  747.546816   
3             320.457282  731.553658        1.0  296.795987  749.779550   
4             320.698215  732.265580        1.0  299.903449  753.269333   
...                  ...         ...        ...         ...         ...   
29992         651.346715  462.211248        1.0  581.673425  434.102119   
29993         651.538346  462.225548        1.0  580.899144  433.592916   
29994         651.453834  462.245982        1.0  580.846196  433.225684   
299

In [ ]:
example_df[]

In [63]:
with h5py.File(h5_path, "r") as f:
    dset_names = list(f.keys())
    locations = f["tracks"][:].T
    tracking_scores = f["tracking_scores"][:]
    instances_scores = f["instance_scores"][:]
    node_names = [n.decode() for n in f["node_names"][:]]


In [64]:
print("===HDF5 datasets===")
print(dset_names)
print()

print("===locations data shape===")
print(locations.shape)
print()

print("===nodes===")
for i, name in enumerate(node_names):
    print(f"{i}: {name}")
print()

===HDF5 datasets===
['edge_inds', 'edge_names', 'instance_scores', 'labels_path', 'node_names', 'point_scores', 'provenance', 'track_names', 'track_occupancy', 'tracking_scores', 'tracks', 'video_ind', 'video_path']

===locations data shape===
(194, 6, 2, 2)

===nodes===
0: ear
1: nose
2: tail_base
3: thorax
4: front_foot
5: rear_foot



In [65]:
locations

array([[[[ 636.18554688, 1315.63500977],
         [ 763.41711426,  764.22235107]],

        [[ 731.88220215, 1207.74133301],
         [ 839.62005615,  835.98730469]],

        [[ 224.43968201,           nan],
         [ 752.24365234,           nan]],

        [[ 444.06677246, 1403.75061035],
         [ 736.12164307,  736.31848145]],

        [[ 559.8215332 , 1287.79211426],
         [ 856.13677979,  883.53204346]],

        [[ 168.12338257,           nan],
         [ 887.70623779,           nan]]],


       [[[ 680.47436523, 1240.11132812],
         [ 764.23657227,  771.94647217]],

        [[ 775.67022705, 1136.28613281],
         [ 840.25872803,  844.39770508]],

        [[ 267.95581055, 1656.20471191],
         [ 787.62969971,  792.44732666]],

        [[ 504.30621338, 1431.85974121],
         [ 728.2098999 ,  743.88330078]],

        [[ 564.33746338, 1279.53369141],
         [ 855.76104736,  879.46813965]],

        [[          nan, 1663.79040527],
         [          nan,  872.431

In [66]:
frame_count, node_count, _, instance_count = locations.shape

print("frame count:", frame_count)
print("node count:", node_count)
print("instance count:", instance_count)

frame count: 194
node count: 6
instance count: 2


In [67]:
from scipy.interpolate import interp1d

def fill_missing(Y, kind="linear"):
    """Fills missing values independently along each dimension after the first."""

    # Store initial shape.
    initial_shape = Y.shape

    # Flatten after first dim.
    Y = Y.reshape((initial_shape[0], -1))

    # Interpolate along each slice.
    for i in range(Y.shape[-1]):
        y = Y[:, i]

        # Build interpolant.
        x = np.flatnonzero(~np.isnan(y))
        f = interp1d(x, y[x], kind=kind, fill_value=np.nan, bounds_error=False)

        # Fill missing
        xq = np.flatnonzero(np.isnan(y))
        y[xq] = f(xq)
        
        # Fill leading or trailing NaNs with the nearest non-NaN values
        mask = np.isnan(y)
        y[mask] = np.interp(np.flatnonzero(mask), np.flatnonzero(~mask), y[~mask])

        # Save slice
        Y[:, i] = y

    # Restore to initial shape.
    Y = Y.reshape(initial_shape)

    return Y

In [68]:
locations = fill_missing(locations)

In [69]:
HEAD_INDEX = 0
THORAX_INDEX = 1
ABDO_INDEX = 2

In [70]:
head_loc = locations[:, HEAD_INDEX, :, :]
thorax_loc = locations[:, THORAX_INDEX, :, :]
abdo_loc = locations[:, ABDO_INDEX, :, :]

In [72]:
locations.shape

(194, 6, 2, 2)

- SLEAP coordinates
    - frame number, node number, x or y, id number

- X coordinate is 0, Y coordinate is 1

In [73]:
locations[0][0]

array([[ 636.18554688, 1315.63500977],
       [ 763.41711426,  764.22235107]])

In [74]:
locations[100][0]

array([[807.97918701, 816.16604614],
       [748.00238037, 769.96801758]])

In [75]:
locations[190][0][1]

array([751.7901001, 755.9498291])

In [76]:
locations[:, 0, 0, 0]

array([ 636.18554688,  680.47436523,  715.9987793 ,  771.855896  ,
        827.88275146,  839.89123535,  835.81665039,  824.12072754,
        820.20666504,  823.92272949,  832.19024658,  839.95068359,
        851.86431885,  852.27661133,  851.9161377 ,  847.76660156,
        836.38787842,  836.37268066,  840.05383301,  852.03717041,
        870.07324219,  888.10931396,  864.08325195,  844.08752441,
        816.04382324,  819.61529541,  848.05718994,  860.03613281,
        883.84130859,  884.40637207,  876.52850342,  859.6038208 ,
        848.3168335 ,  855.93341064,  868.24139404,  855.89404297,
        843.89520264,  860.059021  ,  864.30053711,  864.14373779,
        864.36187744,  831.50213623,  900.09375   ,  907.59606934,
        896.00823975,  895.94885254,  896.15307617,  904.00921631,
        906.17596436,  908.3427124 ,  902.2880249 ,  896.2333374 ,
        896.22851562,  903.61737061,  912.37158203,  919.965271  ,
        936.37457275,  955.89367676,  964.1697998 ,  956.43377

In [77]:
locations.shape

(194, 6, 2, 2)

In [78]:
locations[:,:,:,0]

array([[[636.18554688, 763.41711426],
        [731.88220215, 839.62005615],
        [224.43968201, 752.24365234],
        [444.06677246, 736.12164307],
        [559.8215332 , 856.13677979],
        [168.12338257, 887.70623779]],

       [[680.47436523, 764.23657227],
        [775.67022705, 840.25872803],
        [267.95581055, 787.62969971],
        [504.30621338, 728.2098999 ],
        [564.33746338, 855.76104736],
        [302.61659749, 877.08459473]],

       [[715.9987793 , 760.16168213],
        [816.02160645, 835.62127686],
        [343.76968384, 775.77478027],
        [555.70288086, 731.76989746],
        [727.97674561, 848.21002197],
        [437.10981242, 866.46295166]],

       ...,

       [[407.81848145, 751.7901001 ],
        [440.12734985, 764.06341553],
        [147.87149048, 844.17193604],
        [255.85533142, 720.01757812],
        [436.09719849, 871.95184326],
        [123.85195923, 880.06799316]],

       [[407.81848145, 751.7901001 ],
        [440.12734985, 764.06

In [37]:
def produce_df(rows, columns, row_names=None, column_names=None):
    """rows is a list of lists that will be used to build a MultiIndex
    columns is a list of lists that will be used to build a MultiIndex"""
    row_index = pd.MultiIndex.from_product(rows, names=row_names)
    col_index = pd.MultiIndex.from_product(columns, names=column_names)
    return pd.DataFrame(index=row_index, columns=col_index)

In [43]:
produce_df([['a', 'b']], [node_names, ['x', 'y']])


ear      nose      tail_base      thorax      front_foot      rear_foot  \
     x    y    x    y         x    y      x    y          x    y         x   
a  NaN  NaN  NaN  NaN       NaN  NaN    NaN  NaN        NaN  NaN       NaN   
b  NaN  NaN  NaN  NaN       NaN  NaN    NaN  NaN        NaN  NaN       NaN   

        
     y  
a  NaN  
b  NaN

In [39]:
node_names

['ear', 'nose', 'tail_base', 'thorax', 'front_foot', 'rear_foot']

In [54]:
instances_scores.shape

(2, 194)

In [53]:
tracking_scores

array([[          nan,  -60.09309769, -100.22259521,  -54.80153656,
         -15.63673973,  -10.24626732,   -9.22846603,   -2.67489958,
          -0.32433128,   -0.73331463,   -3.07362914,   -6.64051628,
          -7.30306911,   -3.73756838,   -5.03766775,  -75.62200165,
          -8.53457642,   -7.05034494,  -31.60495567,   -4.25989389,
         -46.05050659,  -38.78982544,  -48.99094391,  -28.59298706,
         -29.63674355,  -26.98335075,   -7.85521555,   -8.05189228,
          -4.20230198,   -6.68486738,   -9.52558708,   -6.74027109,
          -3.03634191,  -48.7921257 ,  -48.12660599,  -53.58452225,
         -58.90586472,  -10.65644264,  -51.15689468,   -1.80665171,
         -22.71046638,  -20.84678459,  -14.03412056,  -24.31245995,
         -22.00974274,   -4.0145793 ,  -31.80082893,  -50.56274414,
          -1.02093506,  -52.80811691,   -1.79668963,  -87.19734192,
         -54.07027817,  -73.33692932,   -9.53038406,   -6.73071575,
         -12.23271179,  -27.28444672,  -47.55476

In [55]:
a=np.arange(24).reshape((3,2,2,2))
iterables=[[1,2,3],[1,2],['m1','m2'],['A','B']]
index = pd.MultiIndex.from_product(iterables, names=['time','sub','meas','cond'])

pd.DataFrame(a.reshape(24, 1),index=index)

0
time sub meas cond    
1    1   m1   A      0
              B      1
         m2   A      2
              B      3
     2   m1   A      4
              B      5
         m2   A      6
              B      7
2    1   m1   A      8
              B      9
         m2   A     10
              B     11
     2   m1   A     12
              B     13
         m2   A     14
              B     15
3    1   m1   A     16
              B     17
         m2   A     18
              B     19
     2   m1   A     20
              B     21
         m2   A     22
              B     23

In [57]:
a.shape

(3, 2, 2, 2)

- Getting all the coordinates for only one animal

In [79]:
locations[:,:,:,0]

array([[[636.18554688, 763.41711426],
        [731.88220215, 839.62005615],
        [224.43968201, 752.24365234],
        [444.06677246, 736.12164307],
        [559.8215332 , 856.13677979],
        [168.12338257, 887.70623779]],

       [[680.47436523, 764.23657227],
        [775.67022705, 840.25872803],
        [267.95581055, 787.62969971],
        [504.30621338, 728.2098999 ],
        [564.33746338, 855.76104736],
        [302.61659749, 877.08459473]],

       [[715.9987793 , 760.16168213],
        [816.02160645, 835.62127686],
        [343.76968384, 775.77478027],
        [555.70288086, 731.76989746],
        [727.97674561, 848.21002197],
        [437.10981242, 866.46295166]],

       ...,

       [[407.81848145, 751.7901001 ],
        [440.12734985, 764.06341553],
        [147.87149048, 844.17193604],
        [255.85533142, 720.01757812],
        [436.09719849, 871.95184326],
        [123.85195923, 880.06799316]],

       [[407.81848145, 751.7901001 ],
        [440.12734985, 764.06

SLEAP coordinates
frame number, node number, x or y, id numberm

In [80]:
locations[:,:,:,0][0]

array([[636.18554688, 763.41711426],
       [731.88220215, 839.62005615],
       [224.43968201, 752.24365234],
       [444.06677246, 736.12164307],
       [559.8215332 , 856.13677979],
       [168.12338257, 887.70623779]])

- Getting coordinates for one animal and one axis

In [82]:
locations[:,:,0,0]

array([[636.18554688, 731.88220215, 224.43968201, 444.06677246,
        559.8215332 , 168.12338257],
       [680.47436523, 775.67022705, 267.95581055, 504.30621338,
        564.33746338, 302.61659749],
       [715.9987793 , 816.02160645, 343.76968384, 555.70288086,
        727.97674561, 437.10981242],
       ...,
       [407.81848145, 440.12734985, 147.87149048, 255.85533142,
        436.09719849, 123.85195923],
       [407.81848145, 440.12734985, 147.87149048, 255.85533142,
        436.09719849, 123.85195923],
       [407.81848145, 440.12734985, 147.87149048, 255.85533142,
        436.09719849, 123.85195923]])

In [83]:
locations[:,:,:,0].shape

(194, 6, 2)

In [85]:
m,n,r = locations[:,:,:,0].shape
out_arr = np.column_stack((np.repeat(np.arange(m),n),locations[:,:,:,0].reshape(m*n,-1)))
out_df = pd.DataFrame(out_arr)

In [86]:
out_df

0           1           2
0       0.0  636.185547  763.417114
1       0.0  731.882202  839.620056
2       0.0  224.439682  752.243652
3       0.0  444.066772  736.121643
4       0.0  559.821533  856.136780
...     ...         ...         ...
1159  193.0  440.127350  764.063416
1160  193.0  147.871490  844.171936
1161  193.0  255.855331  720.017578
1162  193.0  436.097198  871.951843
1163  193.0  123.851959  880.067993

[1164 rows x 3 columns]

In [89]:
locations[:,:,0,0]

array([[636.18554688, 731.88220215, 224.43968201, 444.06677246,
        559.8215332 , 168.12338257],
       [680.47436523, 775.67022705, 267.95581055, 504.30621338,
        564.33746338, 302.61659749],
       [715.9987793 , 816.02160645, 343.76968384, 555.70288086,
        727.97674561, 437.10981242],
       ...,
       [407.81848145, 440.12734985, 147.87149048, 255.85533142,
        436.09719849, 123.85195923],
       [407.81848145, 440.12734985, 147.87149048, 255.85533142,
        436.09719849, 123.85195923],
       [407.81848145, 440.12734985, 147.87149048, 255.85533142,
        436.09719849, 123.85195923]])

In [88]:
locations[:,:,:,0].transpose(2,0,1).reshape(3,-1)

array([[636.18554688, 731.88220215, 224.43968201, ..., 665.32248942,
        752.17095947, 798.02960205],
       [512.1338501 , 639.76861572, 818.686561  , ..., 852.06243896,
        831.59442139, 728.4574585 ],
       [848.08789062, 855.96240234, 796.378479  , ..., 720.01757812,
        871.95184326, 880.06799316]])

In [92]:
locations[:,:,:,0][0]

array([[636.18554688, 763.41711426],
       [731.88220215, 839.62005615],
       [224.43968201, 752.24365234],
       [444.06677246, 736.12164307],
       [559.8215332 , 856.13677979],
       [168.12338257, 887.70623779]])

In [91]:
locations[:,:,:,0][0].shape

(6, 2)

# Getting the coordinates of one animal

- Flattening (3D of frame, node, x or y to 2D of frame, node/x or y)the list so that it can be used in a dataframe
    - https://www.delftstack.com/howto/numpy/convert-3d-array-to-2d-array-in-python/

In [105]:
def convert_single_subj_arr_from_3d_to_2d(single_animal_array):
    """
    """
    return single_animal_array.reshape(single_animal_array.shape[0], (single_animal_array.shape[1]*single_animal_array.shape[2]))

In [114]:
first_animal_2D_arr = convert_single_subj_arr_from_3d_to_2d(locations[:,:,:,0])

- Creating headers for animal one
    - https://stackoverflow.com/questions/32370402/giving-a-column-multiple-indexes-headers

In [115]:
first_animal_header = pd.MultiIndex.from_product([["first_animal"], node_names,
                                     ['x', 'y']],
                                    names=["animal_id", 'body_part','x_or_y'])

In [119]:
first_animal_df = pd.DataFrame(first_animal_2D_arr, columns=first_animal_header)

In [120]:
first_animal_df

animal_id first_animal                                                  \
body_part          ear                    nose               tail_base   
x_or_y               x           y           x           y           x   
0           636.185547  763.417114  731.882202  839.620056  224.439682   
1           680.474365  764.236572  775.670227  840.258728  267.955811   
2           715.998779  760.161682  816.021606  835.621277  343.769684   
3           771.855896  771.493469  867.729797  843.865845  395.809326   
4           827.882751  767.876892  919.877197  839.806763  440.052307   
..                 ...         ...         ...         ...         ...   
189         360.130463  743.406555  455.833435  768.313965  147.871490   
190         407.818481  751.790100  440.127350  764.063416  147.871490   
191         407.818481  751.790100  440.127350  764.063416  147.871490   
192         407.818481  751.790100  440.127350  764.063416  147.871490   
193         407.818481  751.790100  440.127350  764.063416  147.871490   

animal_id                                                              \
body_part                  thorax              front_foot               
x_or_y              y           x           y           x           y   
0          752.243652  444.066772  736.121643  559.821533  856.136780   
1          787.629700  504.306213  728.209900  564.337463  855.761047   
2          775.774780  555.702881  731.769897  727.976746  848.210022   
3          775.524414  623.946594  724.140747  771.931091  864.343689   
4          764.176453  659.968140  723.991455  791.741943  868.098816   
..                ...         ...         ...         ...         ...   
189        844.171936  299.962158  723.643066  436.097198  871.951843   
190        844.171936  255.855331  720.017578  436.097198  871.951843   
191        844.171936  255.855331  720.017578  436.097198  871.951843   
192        844.171936  255.855331  720.017578  436.097198  871.951843   
193        844.171936  255.855331  720.017578  436.097198  871.951843   

animal_id                          
body_part   rear_foot              
x_or_y              x           y  
0          168.123383  887.706238  
1          302.616597  877.084595  
2          437.109812  866.462952  
3          571.603027  855.841309  
4          580.077698  855.778442  
..                ...         ...  
189        127.941246  880.165527  
190        123.851959  880.067993  
191        123.851959  880.067993  
192        123.851959  880.067993  
193        123.851959  880.067993  

[194 rows x 12 columns]

# Combining with the second animal's array

In [117]:
second_animal_2D_arr = convert_single_subj_arr_from_3d_to_2d(locations[:,:,:,1])

In [121]:
second_animal_header = pd.MultiIndex.from_product([["second_animal"], node_names,
                                     ['x', 'y']],
                                    names=["animal_id", 'body_part','x_or_y'])

In [122]:
second_animal_df = pd.DataFrame(second_animal_2D_arr, columns=second_animal_header)

In [123]:
second_animal_df

animal_id second_animal                                                    \
body_part           ear                     nose                tail_base   
x_or_y                x           y            x           y            x   
0           1315.635010  764.222351  1207.741333  835.987305  1656.204712   
1           1240.111328  771.946472  1136.286133  844.397705  1656.204712   
2           1176.172974  779.623596  1084.062378  855.871460  1615.876099   
3           1135.867920  775.867981  1040.480347  844.197449  1515.940430   
4           1099.671265  772.151611   995.635742  832.046387  1468.226440   
..                  ...         ...          ...         ...          ...   
189          575.996582  759.766113   503.568634  767.828308   887.736511   
190          555.968872  755.949829   475.422058  768.286987   839.731934   
191          528.402649  755.987122   416.102570  768.295410   831.920593   
192          511.988922  755.794739   404.093018  771.992798   820.204041   
193          499.726288  756.257812   388.082214  800.332520   811.789124   

animal_id                                                                \
body_part                   thorax               front_foot               
x_or_y              y            x           y            x           y   
0          792.447327  1403.750610  736.318481  1287.792114  883.532043   
1          792.447327  1431.859741  743.883301  1279.533691  879.468140   
2          808.276550  1351.988525  736.108948  1272.240601  880.215332   
3          799.996521  1300.020386  732.340210  1190.092896  872.020844   
4          800.089478  1255.852661  728.207764  1107.945190  863.826355   
..                ...          ...         ...          ...         ...   
189        828.254883   719.773743  724.141541   628.323364  872.386353   
190        815.996460   675.914978  720.318420   615.972046  871.613037   
191        828.133240   655.881226  719.882812   555.444153  871.594727   
192        827.747009   648.287109  720.294006   531.997070  864.419983   
193        827.765259   631.672424  723.493347   480.040375  868.095459   

animal_id                           
body_part    rear_foot              
x_or_y               x           y  
0          1663.790405  872.431580  
1          1663.790405  872.431580  
2          1476.144165  875.805176  
3          1456.408325  852.627502  
4          1287.878418  868.204956  
..                 ...         ...  
189         859.877930  859.913391  
190         787.950378  835.664062  
191         683.661926  860.208069  
192         695.802246  863.527893  
193         688.123108  863.426636  

[194 rows x 12 columns]

- Combining the dataframes for the first and second animals

In [125]:
first_and_second_animal_df = pd.merge(first_animal_df, second_animal_df, left_index=True, right_index=True)

In [126]:
first_and_second_animal_df

animal_id first_animal                                                  \
body_part          ear                    nose               tail_base   
x_or_y               x           y           x           y           x   
0           636.185547  763.417114  731.882202  839.620056  224.439682   
1           680.474365  764.236572  775.670227  840.258728  267.955811   
2           715.998779  760.161682  816.021606  835.621277  343.769684   
3           771.855896  771.493469  867.729797  843.865845  395.809326   
4           827.882751  767.876892  919.877197  839.806763  440.052307   
..                 ...         ...         ...         ...         ...   
189         360.130463  743.406555  455.833435  768.313965  147.871490   
190         407.818481  751.790100  440.127350  764.063416  147.871490   
191         407.818481  751.790100  440.127350  764.063416  147.871490   
192         407.818481  751.790100  440.127350  764.063416  147.871490   
193         407.818481  751.790100  440.127350  764.063416  147.871490   

animal_id                                                              ...  \
body_part                  thorax              front_foot              ...   
x_or_y              y           x           y           x           y  ...   
0          752.243652  444.066772  736.121643  559.821533  856.136780  ...   
1          787.629700  504.306213  728.209900  564.337463  855.761047  ...   
2          775.774780  555.702881  731.769897  727.976746  848.210022  ...   
3          775.524414  623.946594  724.140747  771.931091  864.343689  ...   
4          764.176453  659.968140  723.991455  791.741943  868.098816  ...   
..                ...         ...         ...         ...         ...  ...   
189        844.171936  299.962158  723.643066  436.097198  871.951843  ...   
190        844.171936  255.855331  720.017578  436.097198  871.951843  ...   
191        844.171936  255.855331  720.017578  436.097198  871.951843  ...   
192        844.171936  255.855331  720.017578  436.097198  871.951843  ...   
193        844.171936  255.855331  720.017578  436.097198  871.951843  ...   

animal_id second_animal                                                    \
body_part          nose                tail_base                   thorax   
x_or_y                x           y            x           y            x   
0           1207.741333  835.987305  1656.204712  792.447327  1403.750610   
1           1136.286133  844.397705  1656.204712  792.447327  1431.859741   
2           1084.062378  855.871460  1615.876099  808.276550  1351.988525   
3           1040.480347  844.197449  1515.940430  799.996521  1300.020386   
4            995.635742  832.046387  1468.226440  800.089478  1255.852661   
..                  ...         ...          ...         ...          ...   
189          503.568634  767.828308   887.736511  828.254883   719.773743   
190          475.422058  768.286987   839.731934  815.996460   675.914978   
191          416.102570  768.295410   831.920593  828.133240   655.881226   
192          404.093018  771.992798   820.204041  827.747009   648.287109   
193          388.082214  800.332520   811.789124  827.765259   631.672424   

animal_id                                                                
body_part               front_foot                rear_foot              
x_or_y              y            x           y            x           y  
0          736.318481  1287.792114  883.532043  1663.790405  872.431580  
1          743.883301  1279.533691  879.468140  1663.790405  872.431580  
2          736.108948  1272.240601  880.215332  1476.144165  875.805176  
3          732.340210  1190.092896  872.020844  1456.408325  852.627502  
4          728.207764  1107.945190  863.826355  1287.878418  868.204956  
..                ...          ...         ...          ...         ...  
189        724.141541   628.323364  872.386353   859.877930  859.913391  
190        720.318420   615.972046  871.613037   78

# Renaming Videos

In [172]:
videos = glob.glob("./data/cd1_predicted_frames/*.mp4")

In [183]:
for video in videos:
    video_dirname = os.path.abspath(os.path.dirname(video))
    video_original_filename = os.path.basename(video)
    video_corrected_filename = ".".join([video_original_filename.split(".")[0], "mp4"])
    video_dst_path = os.path.join(video_dirname, video_corrected_filename)
    os.rename(os.path.abspath(video), video_dst_path)

# Starting VAME

In [184]:
import vame

In [185]:
working_directory = "./proc"

In [186]:
project = "tube_test"

In [187]:
videos = glob.glob("./data/cd1_predicted_frames/*.mp4")

- VAME requires the video to be the full path

In [188]:
videos = [os.path.abspath(path) for path in videos]

In [189]:
videos

['/nancy/projects/dominance_strain_comparison/results/2023_03_09_tube_test_sleap_analysis/data/cd1_predicted_frames/CAGE6_TUBETEST_4v1.mp4',
 '/nancy/projects/dominance_strain_comparison/results/2023_03_09_tube_test_sleap_analysis/data/cd1_predicted_frames/CAGE5_TUBETEST_4v1.mp4',
 '/nancy/projects/dominance_strain_comparison/results/2023_03_09_tube_test_sleap_analysis/data/cd1_predicted_frames/CAGE5_TUBETEST_2v3.mp4',
 '/nancy/projects/dominance_strain_comparison/results/2023_03_09_tube_test_sleap_analysis/data/cd1_predicted_frames/CAGE6_TUBETEST_1v3.mp4',
 '/nancy/projects/dominance_strain_comparison/results/2023_03_09_tube_test_sleap_analysis/data/cd1_predicted_frames/CAGE5_TUBETEST_3v4.mp4',
 '/nancy/projects/dominance_strain_comparison/results/2023_03_09_tube_test_sleap_analysis/data/cd1_predicted_frames/CAGE6_TUBETEST_1v2.mp4',
 '/nancy/projects/dominance_strain_comparison/results/2023_03_09_tube_test_sleap_analysis/data/cd1_predicted_frames/CAGE6_TUBETEST_3v4.mp4',
 '/nancy/proj

In [190]:
config = vame.init_new_project(project=project, videos=videos, \
                               working_directory=working_directory, videotype=".mp4")

Created "/nancy/projects/dominance_strain_comparison/results/2023_03_09_tube_test_sleap_analysis/proc/tube_test-Apr16-2023/videos"
Created "/nancy/projects/dominance_strain_comparison/results/2023_03_09_tube_test_sleap_analysis/proc/tube_test-Apr16-2023/data"
Created "/nancy/projects/dominance_strain_comparison/results/2023_03_09_tube_test_sleap_analysis/proc/tube_test-Apr16-2023/results"
Created "/nancy/projects/dominance_strain_comparison/results/2023_03_09_tube_test_sleap_analysis/proc/tube_test-Apr16-2023/model"
Copying the videos 

A VAME project has been created. 

Now its time to prepare your data for VAME. The first step is to move your pose .csv file (e.g. DeepLabCut .csv) into the //YOUR//VAME//PROJECT//videos//pose_estimation folder. From here you can call either the function vame.egocentric_alignment() or if your data is by design egocentric call vame.csv_to_numpy(). This will prepare the data in .csv into the right format to start working with VAME.


# Iterating for each file

In [191]:
from collections import defaultdict

In [192]:
from pathlib import Path

In [193]:
video_to_everything = defaultdict(dict)
pose_output_dir = "./proc/tube_test-Apr16-2023/videos/pose_estimation"

for h5_filepath in glob.glob("./data/cd1_predicted_frames/*h5"):
    with h5py.File(h5_filepath, "r") as f:
        locations = f["tracks"][:].T
        tracking_scores = f["tracking_scores"][:]
        instances_scores = f["instance_scores"][:]
        locations = fill_missing(locations)
    first_animal_2D_arr = convert_single_subj_arr_from_3d_to_2d(locations[:,:,:,0])
    first_animal_df = pd.DataFrame(first_animal_2D_arr, columns=first_animal_header)
    
    second_animal_2D_arr = convert_single_subj_arr_from_3d_to_2d(locations[:,:,:,1])
    second_animal_df = pd.DataFrame(second_animal_2D_arr, columns=second_animal_header)
    
    first_and_second_animal_df = pd.merge(first_animal_df, second_animal_df, left_index=True, right_index=True)
    
    h5_filename = os.path.basename(h5_filepath)
    h5_csv_name = ".".join([h5_filename.split(".")[0], "csv"])
    
    first_animal_df.to_csv(os.path.join(pose_output_dir, h5_csv_name))  
#     first_and_second_animal_df.to_csv(os.path.join(pose_output_dir, h5_csv_name))

In [194]:
h5_filename

'CAGE4_TUBETEST_4v2.fixed.mp4.predictions.000_CAGE4_TUBETEST_4v2.fixed.analysis.h5'

In [195]:
h5_csv_name

'CAGE4_TUBETEST_4v2.csv'

In [196]:
first_and_second_animal_df

animal_id first_animal                                                  \
body_part          ear                    nose               tail_base   
x_or_y               x           y           x           y           x   
0           580.478333  767.671143  672.249695  852.311646  184.026260   
1           648.340759  763.833466  741.872803  844.130981  235.971214   
2           716.203186  759.995789  811.495911  835.950317  287.916168   
3           771.840210  771.726990  855.966431  855.724304  352.149597   
4           807.633301  767.902710  891.867859  847.637451  392.281891   
..                 ...         ...         ...         ...         ...   
179         288.092346  735.966064  300.438171  800.491821   16.220373   
180         272.053619  744.061707  274.372261  774.244110   16.220373   
181         280.100311  760.090942  248.306351  747.996399   16.220373   
182         300.374908  776.179382  343.995972  824.548767   16.220373   
183         300.374908  776.179382  343.995972  824.548767   16.220373   

animal_id                                                              ...  \
body_part                  thorax              front_foot              ...   
x_or_y              y           x           y           x           y  ...   
0          736.277771  407.686340  728.163208  428.322327  844.144470  ...   
1          742.043396  465.775848  727.937439  516.394623  850.216034  ...   
2          747.809021  523.865356  727.711670  604.466919  856.287598  ...   
3          744.360840  571.967041  728.000854  744.303650  867.784546  ...   
4          764.273315  587.963135  727.711182  744.146667  868.268311  ...   
..                ...         ...         ...         ...         ...  ...   
179        795.835754  127.988678  699.951416  283.917358  863.822571  ...   
180        795.835754  116.139946  704.052368  272.055939  864.320190  ...   
181        795.835754  104.272598  712.192444  279.774200  867.558777  ...   
182        795.835754   95.910645  723.572388  284.239044  867.532593  ...   
183        795.835754   95.849869  727.887146  287.712769  864.501831  ...   

animal_id second_animal                                                    \
body_part          nose                tail_base                   thorax   
x_or_y                x           y            x           y            x   
0           1291.812256  835.945984  1783.683472  784.401428  1576.338745   
1           1220.045166  839.930725  1703.853027  791.743225  1508.081055   
2           1148.082031  836.171448  1635.932495  796.010803  1435.947510   
3           1083.862183  839.880615  1547.696777  799.795105  1344.006226   
4           1023.616028  839.991577  1487.926025  803.817200  1275.846802   
..                  ...         ...          ...         ...          ...   
179          300.514709  860.187683   788.264099  775.772949   592.207947   
180          295.646240  828.052246   768.073059  779.513855   591.588928   
181          298.401255  827.871053   773.955780  787.716064   585.757721   
182          301.156270  827.689860   779.838501  795.918274   579.926514   
183          303.911285  827.508667   775.831726  796.138916   596.039917   

animal_id                                                                
body_part               front_foot                rear_foot              
x_or_y              y            x           y            x           y  
0          735.970032  1455.591309  848.525818  1623.724487  880.045105  
1          739.896057  1311.768188  880.352234  1615.812866  876.513000  
2          735.537170  1295.891479  884.214844  1608.455566  876.484924  
3          731.666992  1299.620605  880.411438  1467.830811  863.764099  
4          731.731323  1136.145264  868.334778  1339.774536  876.211670  
..                ...          ...         ...          ...         ...  
179        747.654785   452.235321  871.666077   755.847229  840.386963  
180        744.366150   429.334971  867.794352   75

# Egocentric Alignment

In [197]:
config = os.path.abspath("./proc/tube_test-Apr16-2023/config.yaml")

In [198]:
# vame.egocentric_alignment(config, pose_ref_index=[1,2], crop_size=(300,300), use_video=False, video_format='.mp4', check_video=False)
vame.egocentric_alignment(config, pose_ref_index=[1,2])

Aligning data CAGE6_TUBETEST_4v1, Pose confidence value: 0.99


Align frames: 100%|██████████████████| 170/170 [00:00<00:00, 591.32it/s]


Aligning data CAGE5_TUBETEST_4v1, Pose confidence value: 0.99


Align frames: 100%|██████████████████| 173/173 [00:00<00:00, 795.40it/s]


Aligning data CAGE5_TUBETEST_2v3, Pose confidence value: 0.99


Align frames: 100%|██████████████████| 113/113 [00:00<00:00, 616.78it/s]


Aligning data CAGE6_TUBETEST_1v3, Pose confidence value: 0.99


Align frames: 100%|██████████████████| 238/238 [00:00<00:00, 624.15it/s]


Aligning data CAGE5_TUBETEST_3v4, Pose confidence value: 0.99


Align frames: 100%|██████████████████| 101/101 [00:00<00:00, 585.45it/s]


Aligning data CAGE6_TUBETEST_1v2, Pose confidence value: 0.99


Align frames: 100%|██████████████████| 232/232 [00:00<00:00, 795.07it/s]


Aligning data CAGE6_TUBETEST_3v4, Pose confidence value: 0.99


Align frames: 100%|██████████████████| 295/295 [00:00<00:00, 845.24it/s]


Aligning data CAGE4_TUBETEST_4v1, Pose confidence value: 0.99


Align frames: 100%|████████████████████| 89/89 [00:00<00:00, 521.32it/s]


Aligning data CAGE5_TUBETEST_4v2, Pose confidence value: 0.99


Align frames: 100%|██████████████████| 165/165 [00:00<00:00, 795.02it/s]


Aligning data CAGE4_TUBETEST_1v3, Pose confidence value: 0.99


Align frames: 100%|██████████████████| 503/503 [00:00<00:00, 654.83it/s]


Aligning data CAGE5_TUBETEST_1v2, Pose confidence value: 0.99


Align frames: 100%|██████████████████| 293/293 [00:00<00:00, 690.36it/s]


Aligning data CAGE4_TUBETEST_3v4, Pose confidence value: 0.99


Align frames: 100%|██████████████████| 158/158 [00:00<00:00, 674.89it/s]


Aligning data CAGE6_TUBETEST_2v3, Pose confidence value: 0.99


Align frames: 100%|██████████████████| 147/147 [00:00<00:00, 709.36it/s]


Aligning data CAGE4_TUBETEST_1v2, Pose confidence value: 0.99


Align frames: 100%|██████████████████| 194/194 [00:00<00:00, 567.82it/s]


Aligning data CAGE5_TUBETEST_1v3, Pose confidence value: 0.99


Align frames: 100%|██████████████████| 113/113 [00:00<00:00, 720.85it/s]


Aligning data CAGE6_TUBETEST_4v2, Pose confidence value: 0.99


Align frames: 100%|██████████████████| 191/191 [00:00<00:00, 548.34it/s]


Aligning data CAGE4_TUBETEST_4v2, Pose confidence value: 0.99


Align frames: 100%|██████████████████| 184/184 [00:00<00:00, 572.54it/s]


Aligning data CAGE4_TUBETEST_2v3, Pose confidence value: 0.99


Align frames: 100%|████████████████| 1257/1257 [00:02<00:00, 616.15it/s]

Your data is now ine right format and you can call vame.create_trainset()


In [199]:
vame.create_trainset(config)

Creating training dataset...
Using robust setting to eliminate outliers! IQR factor: 4
Creating trainset from the vame.csv_to_numpy() output 
z-scoring of file CAGE6_TUBETEST_4v1
IQR value: 0.73, IQR cutoff: 2.93
z-scoring of file CAGE5_TUBETEST_4v1
IQR value: 0.98, IQR cutoff: 3.93
z-scoring of file CAGE5_TUBETEST_2v3
IQR value: 1.55, IQR cutoff: 6.21
z-scoring of file CAGE6_TUBETEST_1v3
IQR value: 1.15, IQR cutoff: 4.62
z-scoring of file CAGE5_TUBETEST_3v4
IQR value: 0.86, IQR cutoff: 3.43
z-scoring of file CAGE6_TUBETEST_1v2
IQR value: 1.25, IQR cutoff: 4.98
z-scoring of file CAGE6_TUBETEST_3v4
IQR value: 0.88, IQR cutoff: 3.53
z-scoring of file CAGE4_TUBETEST_4v1
IQR value: 1.00, IQR cutoff: 4.02
z-scoring of file CAGE5_TUBETEST_4v2
IQR value: 1.06, IQR cutoff: 4.22
z-scoring of file CAGE4_TUBETEST_1v3
IQR value: 1.07, IQR cutoff: 4.29
z-scoring of file CAGE5_TUBETEST_1v2
IQR value: 1.32, IQR cutoff: 5.27
z-scoring of file CAGE4_TUBETEST_3v4
IQR value: 1.03, IQR cutoff: 4.10
z-scor

In [ ]:
vame.train_model(config)

Train Variational Autoencoder - model name: VAME 

warning, a GPU was not found... proceeding with CPU (slow!) 

Latent Dimensions: 30, Time window: 30, Batch Size: 256, Beta: 1, lr: 0.0005

Initialize train data. Datapoints 4155
Initialize test data. Datapoints 461
Scheduler step size: 100, Scheduler gamma: 0.20

Start training... 
Epoch: 1
Train loss: 55467.010, MSE-Loss: 35255.142, MSE-Future-Loss 20211.869, KL-Loss: 0.000, Kmeans-Loss: 0.000, weight: 0.00
Test loss: 4306.281, MSE-Loss: 4306.281, KL-Loss: 0.000, Kmeans-Loss: 0.000


Epoch: 2
Train loss: 25053.771, MSE-Loss: 14878.930, MSE-Future-Loss 10174.842, KL-Loss: 0.000, Kmeans-Loss: 0.000, weight: 0.00
Test loss: 2316.809, MSE-Loss: 2316.809, KL-Loss: 0.000, Kmeans-Loss: 0.000


Epoch: 3
Train loss: 18511.259, MSE-Loss: 10866.260, MSE-Future-Loss 7644.076, KL-Loss: 0.325, Kmeans-Loss: 0.598, weight: 0.25
Test loss: 1985.971, MSE-Loss: 1985.065, KL-Loss: 0.567, Kmeans-Loss: 0.339


Epoch: 4
Train loss: 14846.185, MSE-Loss: 884

In [ ]:
vame.evaluate_model(config)

In [ ]:
vame.pose_segmentation()

In [ ]:
vame.community(config, show_umap=False, cut_tree=None)



In [ ]:
vame.motif_videos(config, videoType='.mp4')

In [ ]:
vame.visualization()

In [ ]:
vame.gif(config, pose_ref_index=[0,5], subtract_background=True, start=0, length=500, max_lag=30, label='community', file_format='.mp4', crop_size=(300,300))

# Combining Videos

https://www.geeksforgeeks.org/moviepy-concatenating-multiple-video-files/#